### ISSUE TITLE
当使用正则表达时，选择完全匹配，如果有聊天内容相关，就会报错。

### ISSUE THREAD

**Issue by marc-shen** [cypress0522/thesaurus#4]
Linux下使用本插件。

```yml
^思考.*: ["ummm...?","非常奇怪"]
```

A：我思考人生
骰娘：运行.../program/coc/Dice726724242/mod/thesaurus/script/thesaurus.lua失败:.../program/coc/Dice726724242/mod/thesaurus/script/yaml.lua:703: bad argument #1 to 'sfind' (string expected, got nil)

**Comment by HsiangNianian** [comment]
草，这可是个大坑，我都忘记填了~~（以及忘记怎么填了）~~
我暂时没有Linux环境的bot，如果你是从`ssJSKFJDJ/thesaurus`那下载的，建议重新下载，因为直到前几分钟那边的库才和这边的同步，另外说一下thesaurus的版本。

**Comment by marc-shen** [comment]
就是在这里下载的。
v2.0.3，就是最新的那个release

**Comment by HsiangNianian** [comment]
> 就是在这里下载的。 v2.0.3，就是最新的那个release

无所谓，我会出手。另外你的`^思考.*: ["ummm...?","非常奇怪"]`是前缀匹配，不是完全匹配，完全匹配应该填`^思考$`。
![X54YOUOP4 YM{V18BMH@@VC](https://user-images.githubusercontent.com/44714368/206779003-cc8a0cfa-6231-43e2-9cce-875126aae163.png)

**Comment by HsiangNianian** [comment]
![%9LLAVA~WDQ~KPHGYZU_5YP](https://user-images.githubusercontent.com/44714368/206778285-e791aa16-75ae-4b7c-ba59-444079653667.png)
- Dice版本2.6.5beta12(624+)以上安装方法:

 1. 在 `./DiceQQ/conf/mod/source.list`文件内（没有mod文件夹和这文件就新建）输入 
    ```
    https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/
    https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/
    https://ssjskfjdj.netlify.app/Module/
    ```
 2. 使用 `.system load`命令重载bot，这样做的目的是为了让步骤1里的远程地址生效。
 3. 对bot发送 `.mod get thesaurus`命令，等待安装。
 4. 回到第二步，这样做的目的是为了让mod被加载。

- Dice版本2.6.4b(612+)以上安装方法：

 1. 浏览器访问 `https://github.com/ssJSKFJDJ/thesaurus`并点击绿色按钮 `Code`下的 `Download Zip`按钮下载仓库压缩包。
 2. 解压压缩包，将里面的文件和文件夹全部丢进 `./DiceQQ/mod/`文件夹内。
 3. 使用 `.system load`命令重载。

> tips:遇到无法更新升级的情况请将原本的mod文件删除，你可以把自己的词典`*.yml`文件保存起来，然后下载最新的，再放回去。
